### ISSUE TITLE
Creare gruppi di discussione tematici pluriennali

### ISSUE THREAD

**Issue by lucadonnoh** [csunibo/informabot#101]
spesso non ci sono abbastanza persone in un annata per creare dei gruppi tematici su argomenti di interesse comune (e.g. ai, blockchain, security, code challenges, gaming, rust/go/erlang etc) ma il bot può fare da ponte per creare gruppi che vengono mantenuti verticalmente per diversi anni fino a diventare autosostenibili

**Comment by Flecart** [comment]
Non ho capito esattamente in che modo il bot possa aiutare a fare questo.
Potremmo creare i gruppi e metterci un comando per avere i links ai gruppi.
Però non sto vedendo esattamente quali features servirebbero.

**Comment by foxyseta** [comment]
Non ci sono mai state richieste di gruppi di discussione tematici. Se la cosa cambia, si può assolutamente riaprire questa issue e fornire i collegamenti dal bot.
