### ISSUE TITLE
Possibile refactoring per seguire la struttura convenzionale delle codebase in Go

### ISSUE THREAD

**Issue by paologaleotti** [csunibo/informabot#104]
Solo un suggerimento, sarebbe opportuno utilizzare una [struttura standard](https://github.com/golang-standards/project-layout) dei progetti in go (directory cmd, pkg ecc.)

**Comment by Flecart** [comment]
sembra na buona idea :+1:

**Comment by lucat1** [comment]
Boh in realtà @paologaleotti mi sembra che ci siamo con la struttura. Cosa cambieresti nella pratica alla struttura di informabot?

**Comment by Flecart** [comment]
@lucat1 credo l'organizzazione del codice in modo che segua quel layout.

**Comment by paologaleotti** [comment]
Non è disordinata affatto, era solo una questione di convenzioni, Go è un linguaggio con un sacco di "regole" e convenzioni da seguire imposte da Google, specialmente sulla struttura. Giusto un suggerimento :) del resto è sicuramente più interessante in Go che in node come il vecchio, ottima scelta
