### ISSUE TITLE
`/help_fatherbot`

### ISSUE THREAD

**Issue by foxyseta** [csunibo/informabot#113]
Il comando help autogenera un elenco dei comandi disponibili nel formato:
```
/nomecomando - Descrizione del comando
```
Questo formato è utile per noi utenti umani, perché `/` rende il nome del comando interattivo.

FatherBot, invece, richiede il formato
```
nomecomando - Descrizione del comando
```
per specificare quali sono i comandi che il bot mette a disposizione. Per semplificare il lavoro di chi deve comunicare i nuovi comandi del bot a FatherBot, sarebbe utile aggiungere un comando `/help_fatherbot` il cui risultato sia direttamente inoltrabile a FatherBot senza modifiche (perché già nel formato corretto).

Si tratta quindi di un `/help` senza `/` prefisso nel risultato.

Tenere in considerazione #118.

**Comment by VaiTon** [comment]
Magari escluderei il comando in se dalla lista, in modo tale che sia invocabile solo se se ne conosce l'esistenza

**Comment by foxyseta** [comment]
"Security by obscurity" (da noi è inteso in senso sempre negativo)? Per me rende meno confusionario metterlo pubblico, e non si sa in futuro chi gestisca la nostra o altre istanze del bot. Inoltre non causa spam perché ha la stessa lunghezza di `/help`.

**Comment by VaiTon** [comment]
Più che security era giusto per non aggiungere un comando che servirebbe solo per fini amministrativi, però va bene anche non nasconderlo
