### ISSUE TITLE
`/help`: Bad Request: message is too long

### ISSUE THREAD

**Issue by foxyseta** [csunibo/informabot#118]
Il comando `/help` non dà più risposte, ma non ci sono log di errore. Suppongo che la causa sia qualche modifica del json che porta a non poter più raccogliere l'elenco di tutti i valori dei campi `description`.

**Comment by bogo8liuk** [comment]
Facendo prove in locale, la seguente chiamata:
https://github.com/csunibo/informabot/blob/7012beff70c7929c619f864092411a2dde9d6648/utils/util.go#L17C8-L17C8
mi dà questo errore: `Bad Request: message is too long`

**Comment by foxyseta** [comment]
A proposito: penso che risposte dell'api come `Bad request: message is too long` sarebbe molto ma molto importante loggarle, quindi potremmo fare pure quello.

**Comment by bogo8liuk** [comment]
> Penso che potremmo filtrare via i comandi degli insegnamenti (che sono la stragrande maggioranza e tutti uguali). A livello di codice come soluzione è facilissima. Inoltre accorciare ancora più la descrizione di ogni comando è dura.
> 
> L'alternativa sarebbe mandare una sequenza di messaggi, ma comunque vista la grande quantità di comandi sarebbe una pessima esperienza utente (la chat si "intasa" con un dizionario lunghissimo ed è difficile da consultare).

Sono d'accordo, un ulteriore miglioramento potrebbe essere aggiungere comandi di help specifici che mandano la lista degli insegnamenti di un singolo cdl

**Comment by foxyseta** [comment]
Ah sisi ci sta tipo `/insegnamenti_inf` `/insegnamenti_ing_mag`...

Per fare questo secondo passo aspetterei la chiusura di #111.
