### ISSUE TITLE
Rimuovere _hard coding_ a ID gruppi 

### ISSUE THREAD

**Issue by foxyseta** [csunibo/informabot#121]
https://github.com/csunibo/informabot/blame/f6c357eb3bdf69f380acbda61da9a3cd95c4f235/model/controller.go#L202

Questo abominio sono colpevole io di averlo distrattamente recensito positivamente a un certo punto forse. Pare fosse presente anche prima della riscrittura in Go, e quindi non mi sono messo a risalire all'origine con `git blame` (@Bitrey ?).

Gli id dei gruppi sono presenti in `json/settings.json` e non andrebbero mai harcodati nel codice. Siccome abbiamo la cattiva abitudine di creare gruppi degli anni nuovi ogni volta (a differenza degli insegnamenti), potremmo smettere di usare `settings.json` e cercare la parola chiave "anno" nel titolo del gruppo forse, anche se è solo un'euristica alla buona.

**Comment by musianisamuele** [comment]
Direi che questa è collegata a #128 e #129

**Comment by foxyseta** [comment]
Già. Io fattorizzerei il controllo per i gruppi degli anni in modo che dopo sia richiamabile pure qui. Quindi prerequisito per questa issue diventa #129

**Comment by foxyseta** [comment]
Ora che #129 è chiusa, io sostituirei quel controllo con una chiamata alla stessa funzione di utilità che viene usata là per capire se siamo in un gruppo annuale o meno, commentandola siccome Losco è andato via. @Bitrey sei d'accordo? Così non abbiamo più limiti per `/ludopatico` ma se mai ci fossero problemi scommentiamo il controllo e diventa bandito su ogni gruppo annuale.
