### ISSUE TITLE
/lezionioggi e /lezionidomani per altri cdl

### ISSUE THREAD

**Issue by bogo8liuk** [csunibo/informabot#122]
- da modificare lato sintatti dei comandi (e cioè aggiungere come nuovi comandi) le varianti di `/lezioneoggi(N)` `/lezionidomani(N)` per altri CdL e magistrali. Si può prendere ispirazione dai prefissi che usiamo per le repo, con una differenza: nelle repo non serve disambiguare fra triennali e magistrali perché ci sono insegnamenti diversi, ma in `/lezioneoggi(N)` e `/lezionidomani(N)` sì

_Originally posted by @foxyseta in https://github.com/csunibo/informabot/issues/95#issuecomment-1784202977_

**Comment by bogo8liuk** [comment]
Per i nomi dei comandi delle lezioni di altri corsi, il formato con il trattino alto (e.g. `lezionioggi1-man`) non mi dispiaceva affatto, tuttavia, porta al seguente problema quando viene mandato in un qualsiasi messaggio (e quindi anche nel messaggio di help):
![image](https://github.com/csunibo/informabot/assets/58339191/99b9a1f3-c991-4b32-9ad9-73e6d217c47f)
ovvero che il link cliccabile arriva fino a prima del primo trattino alto, il che rende l'esperienza utente abbastanza fastidiosa perché l'utente dovrebbe scrivere a mano il comando. Si potrebbe pensare di mettere i suffissi tutti attaccati, ma non mi fa impazzire come soluzione, qualcuno ha idee migliori?

**Comment by foxyseta** [comment]
Ah sisi infatti io l'ho sempre scartata come opzione il trattino alto perché è illgale:
> Commands must always start with the / symbol and contain up to 32 characters. They can use Latin letters, numbers and underscores, though simple lowercase text is recommended for a cleaner look.

https://core.telegram.org/bots/features#commands

Per quello nel mio post non li uso. I trattini bassi invece vanno bene se li usiamo con parsimonia.

**Comment by foxyseta** [comment]
@bogo8liuk forse devi fare fetch da main sulla tua fork/branch. Ora usiamo un wrapper go per la API e il webscraping unibo.it che fra l'altro ti permette di esplicitare facilmente anno e CdL credo.

**Comment by boozec** [comment]
Ciao a tutti :wave: mi intrometto nella discussione perché stavo guardando la configurazione per aggiungere i corsi della magistrale a cui, ahimè, bisogna specificare anche il curriculum. Alla fine un messaggio di help lunghissimo:

<details>
  <summary>Messaggio help</summary>
<img src="https://github.com/csunibo/informabot/assets/20584215/2a174b00-7a43-4230-ac76-5b35b0af1419">
</details>

quindi ho pensato che, seguendo il filone anche dell'aggiunta degli altri CdL, potremmo avere un sistema a bottoni come quello seguente al posto dei vari `/lezione(oggi|domani)[_lm_][curriculum]<anno>`. Da questo si seleziona il corso, poi l'anno e poi se guardare per oggi o domani.

![image](https://github.com/csunibo/informabot/assets/20584215/fdc75da6-c310-42bf-bcb5-1ed4e122b646)

**Comment by boozec** [comment]
@bogo8liuk ho modificato il JSON per le magistrali per adesso: posso aprire una PR per aggiungerli così con `/lezioni*` per adesso e nel frattempo lavorare al redesign con i bottoni.

> Va ponderato se mettere i bottoni sotto al messaggio o nella tastiera

Direi solo sotto al messaggio. Si chiama il comando `/lezioni` e da lì vai a step per la selezione.

> ci stai lavorando tu? Nel caso riassegno la issue[...]

Sono novizio di Go, e va riformulata tutta la logica della `actions.json`. Posso provarci però :)

**Comment by bogo8liuk** [comment]
@boozec nel caso contattami pure se hai bisogno di aiuto, nel frattempo riassegno la issue

**Comment by foxyseta** [comment]
> Direi solo sotto al messaggio. Si chiama il comando `/lezioni` e da lì vai a step per la selezione. @foxyseta

Mettere sotto al messaggio significa che CHIUNQUE e non solo l'utente mittente può accedervi.

**Comment by foxyseta** [comment]
Esatto. In chat privata e' indifferente per me. Vedo che la gente lo usa moooolto spesso in gruppo

**Comment by boozec** [comment]
[Screencast 2023-11-21 17:16:07.webm](https://github.com/csunibo/informabot/assets/20584215/7e65d1b6-a0ce-4ac9-925a-e9f811111bf8)

questo è quanto fatto attualmente nella PR collegata a questa issue, che però funziona nella chat privata. Dunque si può estendere poi facilmente da "Oggi" e "Domani" a un generico giorno del calendario. 
(Aggiorna il messaggio ogni volta, non ne invia uno nuovo)

Bisogna capire come farlo nel caso di gruppo. Tu hai idee, @foxyseta ?

**Comment by foxyseta** [comment]
Ah vogliamo pure estendere a giorni diversi da oggi e domani? Telegram non ha un componente UI comodo per la selezione di una data tempo.

Per la generalizzazione al caso della chat di gruppo la cosa che ti preoccupa è come comportarsi quando si può inferire il CdL e l'anno dall'oggetto? Oppure come gestire più utenti che toccano bottoni in modo concorrente?

**Comment by boozec** [comment]
> Ah vogliamo pure estendere a giorni diversi da oggi e domani? 

Si potrebbe in futuro, costruendo un calendario con righe/colonne a simulare i giorni della settimana o del mese.

> quando si può inferire il CdL e l'anno dall'oggetto?

Non so bene come associare il comando al generico gruppo automaticamente al "corso di laurea -> anno di corso", magari rivedo come è scritto attualmente il `/lezionioggi`

**Comment by foxyseta** [comment]
Oddio però una griglia di quelle dimensioni dentro Telegram sembra inusabile. Ma sì una issue possiamo aprirla comunque siccome magari invece è fattibile.

Attualmente usiamo solo parole chiave come "primo", "secondo" e "terzo" per inferire l'anno, ma ovviamente come cosa non scala a CdL diversi (perché l'oggetto del gruppo non riporta mai in modo ragionevole il nome del CdL). Quindi potremmo anche abbandonare in toto l'inferenza e preoccuparci solo del fatto che se io inizio un'operazione altre persone non me la dirottino

**Comment by boozec** [comment]
> Oddio però una griglia di quelle dimensioni dentro Telegram sembra inusabile. 

Magari solo per i prossimi 7 giorni? [¹]

[¹] 
![image](https://github.com/csunibo/informabot/assets/20584215/0ca8cc89-2b9e-47ac-8328-0442dd9e8917)
