### ISSUE TITLE
Messaggio di help troppo lungo

### ISSUE THREAD

**Issue by bogo8liuk** [csunibo/informabot#123]
Dopo l'aggiunta dei nuovi insegnamenti, il comando di help ha un messaggio troppo lungo, infatti, facendo prove in locale, la seguente chiamata:
https://github.com/csunibo/informabot/blob/7012beff70c7929c619f864092411a2dde9d6648/utils/util.go#L17C8-L17C8
mi dà questo errore: `Bad Request: message is too long`

**Comment by foxyseta** [comment]
(Duplicate of #118)
