### ISSUE TITLE
Generalizzare `/cercogruppo` in base al nome del gruppo

### ISSUE THREAD

**Issue by ali-benny** [csunibo/informabot#128]
Per evitare di inserire manualmente in blacklist i gruppi generali degli anni, servirebbe fare come per il comando `/lezioni*` di leggere il titolo del gruppo e cercare, se presente, la parola "anno"

**Comment by musianisamuele** [comment]
Come link la pr #129 ?

**Comment by musianisamuele** [comment]
Ok ce l'ho fatta, come non detto
