### ISSUE TITLE
`/lezioni` nei gruppi

### ISSUE THREAD

**Issue by foxyseta** [csunibo/informabot#143]
Come segnalato in https://github.com/csunibo/informabot/issues/122#issuecomment-1818950752, https://github.com/csunibo/informabot/issues/122#issuecomment-1819041966 e nelle vicinanze, quando lanciamo il comando `/lezioni` in un gruppo, chiunque può anticiparci nel pigiare bottoni e decidere così al posto nostro quali orari visualzzare.

Una soluzione potrebbero essere [le tastiere (tradizionali)](https://github.com/csunibo/informabot/issues/122#issuecomment-1819089069), semplici da usare quanto quelle in linea che usiamo ora, nella speranze che compaiano solo a chi ha mandato il messaggio originale. C'è da chiedersi:
- bisogna dare accesso a tutti i messaggi della chat al bot perché esso consideri i messaggi inviati da tastiera? Sarebbe inutilmente preoccupante per la privacy.
- siamo in grado di distinguere facilmente messaggi inviati tramite tastiera da chi ha invocato il comando iniziale rispetto a messaggi inseriti a mano da altre parti?
- siamo in grado di riconoscere e gestire il caso di un'operazione annullata?

Ovviamente nulla vieta di rimanere con le tastiere in linea come ora, che hanno il privilegio di non generare nuovi messaggi, ma almeno che non le si renda interagibi per terze parti.

**Comment by boozec** [comment]
Ho guardato la cosa e ho visto che c'è un modo carino di farlo [1] ed è supportata dalla [libreria Telegram Go](https://go-telegram-bot-api.dev/examples/keyboard.html#keyboard). C'è un problema però che rende `Keyboard` inutilizabile per questo caso d'uso, e mi riferisco alle mancate callback. L'utente, quando clicca il bottone, invia un messaggio con tale testo al bot (o nel gruppo): questo vuol dire che il bot deve gestire tutti i messaggi che gli arrivano e vedere se fanno match con qualcosa, ma in questo caso dovremmo fare sequenzialmente gli step corso -> anno -> giorno.
Il flow però è meno elegante, perché non parliamo più di comandi o callback; oltre al possibile spam dentro un gruppo.

[1] 
![photo_6030641478591692242_y](https://github.com/csunibo/informabot/assets/20584215/e1d13516-60f9-4a5c-9ccf-fe0f4480d1eb)

**Comment by foxyseta** [comment]
Dovremmo anche dare accesso al bot ai messaggi che non cominciano per / nelle autorizzazioni?

**Comment by musianisamuele** [comment]
La mancanza di callback per per `Keyboard` e la necessità di mandare tutti i messaggi sul gruppo per capire che lezioni mandare mi fa pensare che la soluzione attuale sia la migliore

**Comment by foxyseta** [comment]
Sisi aspettavo proprio una scusa definitiva per bocciarla come cosa. Sembra una funzionalità progettata un po' a metà almeno nel caso dei gruppi.

Ad ogni modo, anche usando le tastiere in linea (sotto al messaggio) come ora, possiamo comunque filtrare i callback in base al mittente. Quindi se in futuro vediamo che succedono malestri con gente che si ruba i comandi a vicenda possiamo comunque sistemare in altro modo. Se anche a voi soddisfa la situa attuale possiamo chiudere come "Non programmata". Dopotutto in queste settimane non sono successi casini.

**Comment by musianisamuele** [comment]
Per me va bene chiudere. La cosa di filtrare il mittente sulla callback potrebbe avere un senso. Magari il blocco è solo per i primi minuti in cui il comando è stato mandato e poi dopo possono farlo tutti. Per me questa è una feature che possiamo implementare
