### ISSUE TITLE
/rappresentanti

### ISSUE THREAD

**Issue by Jabbar03** [csunibo/informabot#146]
Questo comando dovrebbe taggare tutti i rappresentanti del corso di Informatica della Triennale e Magistrale di Bologna.

**Comment by musianisamuele** [comment]
Direi decisamente meglio della proposta di prima :)

Essendo ora il bot legato a tutto il disi come vogliamo elencare i rappresentanti? Perché ovviamente noi non copriamo ne ingegneria ne cesena, di conseguenza il comando dovrebbe poterli elencare tutti.

**Comment by Jabbar03** [comment]
Pensavo un po' come i mantainer. Fare un campo che identifica il "gruppo" di cui fai parte e uno che elenchi quali sono le persone. Se vogliamo differenziarli all'interno di un "gruppo" per anno andranno modificati ogni anno, cosa abbastanza scomoda. Perciò direi di mettere solo un lista dato che qua gli array non vengono apprezzati.

**Comment by Jabbar03** [comment]
Es:
Città:
     Corso:
          Elenco persone:  
          (tag di telegram)

**Comment by musianisamuele** [comment]
Per me ci può stare, procedi pure. In questo caso per le persone comunque l'array va benissimo ahaha

**Comment by Jabbar03** [comment]
Ho dei dubbi su come facciamo a distingure le chiamate del bot perchè non possiamo sempre stampare tutti i rappresentanti, quando facciamo il comando dovremmo anche scrivere di quale corso tipo /rappresentanti@(codicecorso). 
I miei dubbi sono sul fatto che @(codicecorso) com'è codificato? è parte del comando?

**Comment by foxyseta** [comment]
Siccome vogliamo renderlo il più intuitivo da usare configlio bottoni nella UI (tastiera o tastiera in linea). Confrontati @boozec magari che sta studiando la stessa cosa per il comando `/lezioni` che puoi già collaudare in produzione.
