### ISSUE TITLE
Il restart del bot non salva i gruppi

### ISSUE THREAD

**Issue by musianisamuele** [csunibo/informabot#148]
Se il bot viene fermato e poi riavviato tutti i gruppi formati con il comando /cercogruppo vengono persi perché sono salvati in ram. Andrebbero salvati in un db locale (magari sqlite) in modo che al restart si controlli se questo db esiste e nel caso si ricaricano i gruppi

**Comment by foxyseta** [comment]
Scusa non sono salvati in `groups.json`?
