### ISSUE TITLE
Aggiornamenti automatici per il contenuto della Bacheca

### ISSUE THREAD

**Issue by maforn** [csunibo/informabot#167]
Spesso e volentieri sulla [bacheca](https://corsi.unibo.it/laurea/informatica/bacheca) dei corsi di laurea vengono messe informazioni utili come pubblicazioni bandi, borse di studio ed eventi che nessuno guarda perché non c'è effetivamente un sistema di notifiche.  
La bacheca ha un feed [rss](https://corsi.unibo.it/laurea/informatica/bacheca/rss.xml), perciò io e @MattiaFerrarini pensavamo di aggiungere una nuova parte al bot per controllare ogni giorno e mandare gli update agli interessati.  
L'idea generale è questa e intanto chiediamo approvazione, rimangono però dubbi su come mantenere lo storico degli eventi e come effettivamente mandare le notifiche. Sarebbe meglio fare un canale apposito per ogni corso di laurea, scrivere direttamente nei gruppi dei corsi o dare la possibilità alla gente di iscriversi uno ad uno?

**Comment by samuelemusiani** [comment]
Ciao, a me sembra una bella idea da portare avanti!

> rimangono però dubbi su come mantenere lo storico degli eventi

Non ho capito cosa itendi. Assumendo esista un sistema di notifica (qualunque esso sia), quando esce un nuovo _post_ viene mandata la notifica. Se non si è ancora iscritti alle notifiche non si riceve il messaggio. Si riceveranno quindi solo quelli pubblicati dopo l'iscrizione.

> Sarebbe meglio fare un canale apposito per ogni corso di laurea, scrivere direttamente nei gruppi dei corsi o dare la possibilità alla gente di iscriversi uno ad uno?

1. Se si crea un canale apposito per ogni corso di laurea lo si può fare in parallelo a questo bot. Volendo si potrebbe integrare anche in questo, ma andrebbero hardcodati gli id delle chat e complicata la logica e non mi piace così stanto. Se questa fosse la direzione potremmo fare semplicemente un bot a parte che manda solo notifiche ed evita di complicare questo.
2. Eviterei di scrivere direttamente nei gruppi dei corsi di laurea per non creare più spam già di quanto sia già presente.
3. L'idea secondo me migliore, soprattuto se vogliamo integrarlo in questo bot, è permettere una sorta di comando `/iscrivi` che funziona solo in chat privata e che permette di ricevere singolarmente le notifiche. Dovremmo comunque salvarci in locale le persone iscritte, ma direi che non è un problema particolarmente grosso.

Mi piacrebbe sentire l'opinione anche di altri @csunibo/sviluppatori-bot.

Samuele

**Comment by foxyseta** [comment]
Esistono già bot che permettono sottoscrizione a feed RSS mandando il link al feed. Il problema che stiamo cercando di risolvere è che la gente non sa come funzioni RSS/non sa che esistano/dove trovare i feed che sta cercando?

**Comment by maforn** [comment]
> Non ho capito cosa itendi

Intendo dire che dovremmo poter scrivere da qualche parte gli eventi già notificati per essere sicuri di non mandarli due volte.



> Il problema che stiamo cercando di risolvere è che la gente non sa come funzioni RSS/non sa che esistano/dove trovare i feed che sta cercando?

Esattamente. Possiamo anche aggiungere solo un opzione per rimandare la gente a uno di questi bot, però mi pareva un po' triste.

**Comment by foxyseta** [comment]
> Esattamente. Possiamo anche aggiungere solo un opzione per rimandare la gente a uno di questi bot, però mi pareva un po' triste, anche se probabilmente è la più funzionale.

Ci risparmierebbe di reinventare la ruota, che va sempre evitato. Si può creare un solo gruppo a cui aggiungere sti bot dove se non sei admin/bot non puoi scrivere. Così tutta la spam è lì in un'unica chat e chi non vuole non entra/silenzia.

**Comment by foxyseta** [comment]
bump
