### ISSUE TITLE
`/admstaff` `/account`

### ISSUE THREAD

**Issue by FoxySeta** [csunibo/informabot#39]
@SF-ZeBug, potresti aggiungere un comando `/admstaff` e uno `/account` (semplici messaggi).
Supportiamo HTML e emoji, ma puoi fare solo lo scheletro e poi alla formattazione ci penso io se lasci la spunta "Autorizza modifiche da parte dei mantenitori" dalla tua PR.

**Comment by ali-benny** [comment]
ho appena aggiunto admstaff ho letto ora l'issue ahahha opsiii

**Comment by ali-benny** [comment]
in /account cosa vorresti mettere?

**Comment by ali-benny** [comment]
Okay /account doveva servire per dare il link agli account di laboratorio ma non è così utile e teniamo solo /admstaff
