### ISSUE TITLE
Riscrittura in Go

### ISSUE THREAD

**Issue by foxyseta** [csunibo/informabot#59]

**Comment by lucat1** [comment]
ahahahah perché non in go o rust o [inserisci linguaggio qui]

**Comment by foxyseta** [comment]
Se avrò il tempo io mi proporrei per Go. Rust sarebbe solo per il meme nel mio caso.

**Comment by lucat1** [comment]
Rust meme molto divertente, però si Go è più approcciabile per un neofita e quindi più persone possono contribuire nel futuro. L'obbiettivo di evitare riscritture il prossimo anno direi che c'è ancora.

**Comment by crestaa** [comment]
Mi associo per Go se serve

**Comment by foxyseta** [comment]
@crestaa quando hai tempo dovresti fare un rebase da main in seguito a #63, che contiene un nuovo comando (o banalmente reimplementarlo nella tua branch a mano già che stai traducendo). Ho dovuto fargliela fare subito per il meme, ma ovviamente ho messo in pausa tutte le altre issue su questa repo per dare precedenza al tuo lavoro. In bocca al lupo e grazie ancora 💪🏼

**Comment by crestaa** [comment]
@foxyseta ho provato a creare il progetto [qui](https://github.com/orgs/csunibo/projects/10) per avere a portata tutta la lista di cose da fare/idee nuove da implementare, se ho fatto casini sentiti liberissimo di editare

**Comment by foxyseta** [comment]
@crestaa se aggiungo un comando `/wiki` testuale semplice al json su main è un problema? Perché la wiki andrebbe spammata a breve.

**Comment by crestaa** [comment]
@foxyseta aggiungi pure, appena riesco faccio un pull da main

**Comment by foxyseta** [comment]
Aggiunto ma ti dico quando lo avrò anche testato in produzione.

**Comment by foxyseta** [comment]
Testato. Puoi fare un merge da main quando vuoi.
