### ISSUE TITLE
Rimuovi /aggiorna

### ISSUE THREAD

**Issue by foxyseta** [csunibo/informabot#60]
/aggiorna ha smesso di andare quando abbiamo spostato Informabot sulla nuova macchina di laboratorio.

**Comment by lucat1** [comment]
Con macchina di laboratorio intendi la vm di adm?

**Comment by foxyseta** [comment]
Sì. Non ho investigato ma ho setuppato il servizio a caso quindi magari va aggiornata di conseguenza la logica di /aggiorna

**Comment by foxyseta** [comment]
Il comando `/aggiorna` è dipendente dal setup e pure concettualmente insicuro. Andrebbe rimosso. Quando si vuole aggiornare il bot, che si chieda ai @csunibo/sistemisti.

**Comment by foxyseta** [comment]
Closed by #81
