### ISSUE TITLE
Make user-friendly Pull requests for [csunibo.github.io/*] from TelegramBot

### ISSUE THREAD

**Issue by maxozolin** [csunibo/informabot#64]
Make the telegram bot handle PRs for adding notes/files to csunibo.

Flow idea: 
1. Get file/files and where to put the file/files from user
2. Check name, conformity etc... if does not conform handle or reject
3. Authenticate with designated TGBot github account
4. Make a fork of the requested repo with the TGBot github account
5. Commit the file/files with metadata to the fork, in a form that is equivalent to`git commit -m 'Telegram user [id]: [Name] [Handle] [etc...] commited file [File_Name]'`
6. Make a Pull request
7. Delete the fork (Should be able to delete the fork even before it is accepted as a pr, but not sure)

**Comment by foxyseta** [comment]
Riporto qui quanto accennato IRL per i posteri: al momento in #59 @crestaa sta lavorando a una riscrittura in Go che si è resa necessaria e consigliata da un bel po' di persone da molto tempo. (Il bot era inizialmente in Javascript solo perché ci fu consegnato così dagli immatricolati nell'a.a. 2019/20). Questo fa parte di un progetto più ampio: https://github.com/orgs/csunibo/projects/4.
Per le funzionalità così grosse consiglio di aspettare dopo la riscrittura per non doverle reimplamentare due volte. Se non siete troppo a vostro agio in Go/non avete voglia di impararlo solo per questa PR, avete fatto bene ad aprire questa issue, che resta disponibile per ogni altra o altro contribuente.

**Comment by foxyseta** [comment]
Ciao! Ora che grazie a @crestaa e @Flecart la riscrittura in Go è ultimata, potete prima chiedere consigli sul gruppo Telegram e poi eventualmente aprire una PR che risolva questo issue.

**Comment by VaiTon** [comment]
@foxyseta quindi questa la chiudiamo?

**Comment by maxozolin** [comment]
Sì, al momento non ho tempo per lavorarci e in retrospettiva non so quanto sia effettivamente richiesta.

Quindi direi di chiudere e se mai ho un riscontro che sarebbe effettivamente utile a qualcuno vedo di farlo in futuro.
