### ISSUE TITLE
comandi base con risposta testuale

### ISSUE THREAD

**Issue by crestaa** [csunibo/informabot#66]

**Comment by Flecart** [comment]
Secondo me una cosa molto brutta dell'implementazione in JS precedente è il fatto che alle funzioni bisogna passare un sacco di `action.cose`. Potremmo creare una struttura che rappresenti tutte le informazioni della singola action per comando?
E anche un convertitore, che prenda in input il pezzo di json, che sarebbe l'action e ritorni la struttura action adeguata.
Sarebbe un buon pattern secondo te?

**Comment by Flecart** [comment]
https://www.what-could-possibly-go-wrong.com/the-dispatcher-pattern/ credo questo sia il pattern che cerchiamo per la funzione `act`
