### ISSUE TITLE
Struttura alternativa del JSON `actions`

### ISSUE THREAD

**Issue by Flecart** [csunibo/informabot#72]
## Introduzione
La struttura actions all'interno di Informabot è la struttura principale da cui il bot va a ritorvare le informazioni necessarie per rispondere in modo appropriato. Attualmente possiede una struttura molto piatta:
1. Definizione nome-comando
2. definizione del tipo di comando
3. Dati variabili, allo **stesso livello** del tipo di comando.

### Richiesta:
La questione che vorrei sollevare è mettere tutti i campi dati, che sono variabili e differenti a seconda della tipologia di comando, in un suo livello di indentazione. Questo faciliterebbe molto la sezione di parsing del JSON (andrebbe a guardare il tipo, e poi parserebbe a seconda del tipo), e renderebbe anche molto più chiara l'interfaccia di `act`.

## Esempi
Attualmente abbiamo cose come 
```json
  "start": {
    "type": "message",
    "text": "..."
  },
  "cercogruppo": {
    "type": "lookingFor",
    "description": "Cerca un gruppo di progetto",
    "singularText": "Una persona cerca un gruppo in <b>\"{0}\"</b>:\n",
    "pluralText": "<b>{1}</b> persone cercano gruppi in <b>\"{0}\"</b>:\n",
    "chatError": "Questo comando è riservato alle chat dei gruppi degli insegnamenti."
  },
```

Secondo me sarebbe più chiaro avere una forma di questo tipo

```json
  "start": {
    "type": "message",
    "data": {
        "text": "...."
     }
  },
  "cercogruppo": {
    "type": "lookingFor",
    "data": {
        "description": "Cerca un gruppo di progetto",
        "singularText": "Una persona cerca un gruppo in <b>\"{0}\"</b>:\n",
        "pluralText": "<b>{1}</b> persone cercano gruppi in <b>\"{0}\"</b>:\n",
        "chatError": "Questo comando è riservato alle chat dei gruppi degli insegnamenti."
    }
  },
```

**Comment by Flecart** [comment]
## Script
Uno script in python  per eseguire l'operazione sopra descritta:

```python3

import json

with open('json/actions.json') as f:
    data = json.load(f)
  
result_json = dict()

for keyword in data:
    command = data[keyword]

    new_data_field = dict()

    to_delete = []
    for field in command:
        if field != 'type':
            new_data_field[field] = command[field]
            to_delete.append(field)
    
    for field in to_delete:
        del command[field]
    
    command['data'] = new_data_field
    result_json[keyword] = command

with open("result.json", "w") as f:
    json.dump(result_json, f, indent=2)
```

**Comment by foxyseta** [comment]
Al momento @crestaa sta riscrivendo in Go, in cui il parsing viene effettuando facendo marshaling direttamente nel tipo di struct desiderato. Quindi il modo non-piatto in cui strutturare i json sarà lo stesso in cui lui definisce i tipi di struct in Go.
Si potrebbero usare i generici, dove Data è il tipo della struct innestata che contiene i campi variabili.
