### ISSUE TITLE
Rispondere sullo stesso canale da cui proviene l'innesco

### ISSUE THREAD

**Issue by foxyseta** [csunibo/informabot#73]
Ora che il gruppo del primo anno ha due canali, ci siamo accorti che il bot manda messaggi sempre e solo su quello principale. Questo perché è stato scritto prima che Teelgram introducesse i canali.

**Comment by foxyseta** [comment]
La PR in JS risolveva correttamente il problema, che però è rispuntato fuori dopo la traduzione in Go. Magari la PR è stata accettata dopo che quella parte è stata tradotta.

**Comment by musianisamuele** [comment]
Ho letto un po' tra le API che stiamo usando e i topic non sono ancora stati implementati. C'è una issue aperta al riguardo (https://github.com/go-telegram-bot-api/telegram-bot-api/issues/622). 

La buona notizia e che esiste una PR (https://github.com/go-telegram-bot-api/telegram-bot-api/pull/663) in cui vengono inseriti tutti i metodi necessari affinché si possa interagire con i topics, ma non è stato ancora fatto il merge. Direi quindi che l'unica opzione sensata è per il momento di aspettare e sperare che quella PR venga accettata il prima possibile.

**Comment by foxyseta** [comment]
Sì, ok. Anche io penso non sia urgente sicome solo @csunibo usa i topics. Se in futuro anche i gruppi degli anni volessero usare i topic e questa PR fosse pronta al merge, potremmo lavorare su un fork nostro fino al merge.

**Comment by Flecart** [comment]
risolta da #103
