### ISSUE TITLE
scrittura test Go

### ISSUE THREAD

**Issue by crestaa** [csunibo/informabot#85]

**Comment by foxyseta** [comment]
In @csunibo/sviluppatori-bot forse qualcuna o qualcuno è interessata o interessato?

**Comment by foxyseta** [comment]
Chiudo per mancanza di interesse.

**Comment by foxyseta** [comment]
@crestaa avevi già fatto qualche piccolo test in `test-code`. Ho fatto un rebase da main. Se riesci a sistemare il/i test che fallisce/falliscono possiamo intanto integrare in `main` quello che avevi già fatto.

**Comment by crestaa** [comment]
@foxyseta si, avevo fatto qualche piccolo test. Al momento a livello di tempistiche faccio fatica, appena ho tempo provo a darci un occhio e sistemo quel che fallisce.
