### ISSUE TITLE
Rimuovere virtuale, teams, website

### ISSUE THREAD

**Issue by foxyseta** [csunibo/informabot#86]
I comandi degli insegnamenti includono informazioni non più aggiornate da anni:
- Teams (dai tempi della DaD);
- Virtuale (ogni anno il link cambia e non possiamo pretendere che sia tenuto sempre aggiornato);
- sito del corso (idem).

Queste tre voci andrebbero rimosse dai comandi degli insegnamenti di `actions.json`. Andrebbero inoltre adattate le strutture dati Go in questione per rimuovere il supporto di questi tre campi.

È un lavoro abbastanza facile se qualcuna o qualcuno in @csunibo/sviluppatori-bot ha voglia di darci un'occhiata.

**Comment by Flecart** [comment]
come mai anche il sito del corso?

**Comment by foxyseta** [comment]
Perché mi sono accorto solo dopo che salvo cambi di  CPU il codice è quello per tutti gli ann😅 Quindi in realtà il sito dell'insegnamento l'ho tenuto: https://github.com/csunibo/informabot/commit/85d5c443fdb7eed4d6b4b992e8b262d02868ee0e
