### ISSUE TITLE
Link a Virtuale ottenuto automaticamente facendo scraping

### ISSUE THREAD

**Issue by konova8** [csunibo/informabot#89]
Fare in modo che il link a virtuale del corso venga preso facendo web scraping dalla pagina del corso, così da includerlo nel messaggio che manda il bot relativo ai singoli corsi

Proverò a farlo io in questi giorni, non è qualcosa di urgente visto che comunque è facilmente reperibile

**Comment by foxyseta** [comment]
Chiudo per:
- mancanza di interesse (aperta da aprile);
- con l'aggiunta di nuove istanze, inoltre, i comandi relativi agli insegnamenti sono già assai verbosi;
- significa fare una richiesta a unibo.it per i comandi degli insegnamenti, e quindi trasformare questi comandi minimali in operazioni asincrone.

Se proprio si vuole comunque implementare, questa issue possiamo riaprirla senza problemi.
