### ISSUE TITLE
Inserimento badge "test coverage" nel README

### ISSUE THREAD

**Issue by crestaa** [csunibo/informabot#90]
Dopo aver aggiunto i test delle varie funzioni sarebbe carino inserire alcuni badge nel readme, tra cui

- [ ] [code coverage](https://hackernoon.com/adding-test-coverage-badge-on-github-without-using-third-party-services/)
- [ ] licenza
- [ ] successo test
- [ ] versione di Go

**Comment by foxyseta** [comment]
Visto che alla fine i test sono proprio pochi magari quelli evitiamo ahahahah Però per tutti gli altri sì. Ho taggato questa issue come "good first issue" perché alla portata di una matricola (una volta che le si spiega cosa siano i badge).

**Comment by foxyseta** [comment]
Bump @crestaa

**Comment by foxyseta** [comment]
I test se non sono già mergiati puoi mergiali comunque finché fanno. Abbiamo anche una CI/CD che li lancia mi pare
