### ISSUE TITLE
@csunibo per taggare i mantainer 

### ISSUE THREAD

**Issue by ali-benny** [csunibo/informabot#93]
Sarebbe carino se in tutti i gruppi ci potessero taggare con @csunibo e il bot inoltrasse il messaggio nel nostro gruppo csunibo-risorse.
Il motivo principale è per non perdere file/foto di esami che potrebbero essere caricati

**Comment by foxyseta** [comment]
Sembra molto facile, ora che è stato aggiunto `autoreply.json`. Ho taggato come "good first issue" perché è alla portata di una matricola.
