### ISSUE TITLE
Ri-considerare il layout dei comandi per altri corsi

### ISSUE THREAD

**Issue by VaiTon** [csunibo/informabot#95]
Al momento i comandi sono specifici per Informatica. Se vogliamo estendere l'utilità a vari corsi è necessario generalizzare i comandi, o almeno "conservare" delle informazioni sugli utenti per capire di che "primo anno" si parli.

**Comment by lucat1** [comment]
Ah si, io generalizzerei. Mi pare più semplice. In alternativa,  potremo mettere sempre tutti gli output per tutti i corsi di laurea ad ogni comando. Non è scalabile come cosa, ma andrebbe per ora.

**Comment by foxyseta** [comment]
Si' mi sembra molto importante come cosa.

**Comment by Flecart** [comment]
Avrebbe senso secondo me tenere i comandi separati come suggerisce foxy, (mi riferisco a
> Es. /orari-ing-1 per ingegneria, /orari-inf-3 per informatica, /orari-man-2 per management, /orari-ingsci-2 per ing&sci

Aggiungerei la possibilità di configurare da telegram gli alias dei comandi di default come `/orari`, e simili.
Oppure invece di configurare a mano ogni singolo comando potrebbe essere comodo poter lasciare la possibilità all'admin di selezionare il _set di alias_ voluto.
Ossia configuriamo il _set di alias_ info_primo_anno che puntano ad orari del primo anno, e corsi del primo anno, set di alias per il secondo anno per i link del secondo anno etc.
Lo farei fare all'utente perché hardcodare id del gruppo o convezione nel nome come facciamo ora è molto rigida come cosa seconod me.

Per i corsi ci sono corsi in particolare che coincidono di nome oppure non c'è sto problema?

**Comment by foxyseta** [comment]
Al momento gli "insiemi di alias" (1/2/3) sono inferiti dal nome del gruppo. Se il nome del gruppo non è autoesplicativo, il bot risponde elencando le possibilità. Basta poi cliccare su quella giusta.

Per gli insegnmenti, al momento non esiste nessun duplicato, perché Ingegneria mette `-T` alla fine di tutto, Scienze e Ingegneria Informatica di Cesena usa whatsapp anziché telegram (potremmo chiedere sul gruppo se abbiano intenzione di cambiare anno prossimo) e Management ha rifiutato collaborazioni.

**Comment by foxyseta** [comment]
Visto che gli insegnamenti non danno problemi rimangono,

- da modificare lato sintatti dei comandi (e cioè aggiungere come nuovi comandi) le varianti di `/lezioneoggi(N)` `/lezionidomani(N)` per altri CdL e magistrali. Si può prendere ispirazione dai prefissi che usiamo per le repo, con una differenza: nelle repo non serve disambiguare fra triennali e magistrali perché ci sono insegnamenti diversi, ma in `/lezioneoggi(N)` e `/lezionidomani(N)` sì;
- da modificare lato applicativi puntati dal bot `/coursedesc` (basta aprire una issue nella repo di riferimento e poi ci si penserà)
- da modificare lato risposta statica del bot `/scelta` nel caso in altri CdL si possano scegliere esami a scelta da altri SSD, `/registrate` per aggiungere quelle di altri CdL.

Forse aprirei issue separate ora che abbiamo ben identificato i comandi da cambiare (che sono di tipologie anche molto diverse). @bogo8liuk sei d'accordo?

**Comment by bogo8liuk** [comment]
> Visto che gli insegnamenti non danno problemi rimangono,
> 
>     * da modificare lato sintatti dei comandi (e cioè aggiungere come nuovi comandi) le varianti di `/lezioneoggi(N)` `/lezionidomani(N)` per altri CdL e magistrali. Si può prendere ispirazione dai prefissi che usiamo per le repo, con una differenza: nelle repo non serve disambiguare fra triennali e magistrali perché ci sono insegnamenti diversi, ma in `/lezioneoggi(N)` e `/lezionidomani(N)` sì;
> 
>     * da modificare lato applicativi puntati dal bot `/coursedesc` (basta aprire una issue nella repo di riferimento e poi ci si penserà)
> 
>     * da modificare lato risposta statica del bot `/scelta` nel caso in altri CdL si possano scegliere esami a scelta da altri SSD, `/registrate` per aggiungere quelle di altri CdL.
> 
> 
> Forse aprirei issue separate ora che abbiamo ben identificato i comandi da cambiare (che sono di tipologie anche molto diverse). @bogo8liuk sei d'accordo?

Sì, sono d'accordo, apro la issue sui comandi delle lezioni

**Comment by foxyseta** [comment]
> Visto che gli insegnamenti non danno problemi (stanno venendo inclusi in #111) rimangono,
> 
> * da modificare lato sintatti dei comandi (e cioè aggiungere come nuovi comandi) le varianti di `/lezioneoggi(N)` `/lezionidomani(N)` per altri CdL e magistrali. Si può prendere ispirazione dai prefissi che usiamo per le repo, con una differenza: nelle repo non serve disambiguare fra triennali e magistrali perché ci sono insegnamenti diversi, ma in `/lezioneoggi(N)` e `/lezionidomani(N)` sì; ([/lezionioggi e /lezionidomani per altri cdl #122](https://github.com/csunibo/informabot/issues/122))
> * da modificare lato applicativi puntati dal bot `/coursedesc` ([Aggiungere altri CdL del DISI course-description-merged#21](https://github.com/csunibo/course-description-merged/issues/21))
> * da modificare lato risposta statica del bot `/scelta` nel caso in altri CdL si possano scegliere esami a scelta da altri SSD, `/registrate` per aggiungere quelle di altri CdL. ([Estendere "Scelta" e "Registrate" anche ad altri CdL #134](https://github.com/csunibo/informabot/issues/134))
> 
> Forse aprirei issue separate ora che abbiamo ben identificato i comandi da cambiare (che sono di tipologie anche molto diverse). @bogo8liuk sei d'accordo?

Questa analisi per casi si è riveltata esaustiva. Quindi questa issue generalista viene chiusa e sostituita da:
- [ ] #111
- [ ] #122
- [ ] #134
- [ ] https://github.com/csunibo/course-description-merged/issues/21
