### ISSUE TITLE
Utilizzare una libreria condivisa per l'accesso alle API di Unibo

### ISSUE THREAD

**Issue by VaiTon** [csunibo/informabot#99]
- ~[calendario](https://github.com/VaiTon/unibocalendar/tree/main/unibo) (possiamo anche forkare, così da avere un pkg su csunibo)~
- ~[bot telegram](https://github.com/csunibo/informabot)~

- [x] Creare la libreria[^1]
- [ ] Utilizzare la libreria in informabot

[^1]: la libreria è collocata presso https://github.com/csunibo/unibo-go.

**Comment by VaiTon** [comment]
Penso che già sia utilizzabile. Sarebbe utile avere una lista di feature da considerare per l'implementazione nella libreria.

**Comment by foxyseta** [comment]
Potrei fare una lista TODO in una nuova issue su https://github.com/csunibo/unibo-go. Poi puoi spuntare le voci che sono già implementate o cancellare quelle che pensi non andrebbero aggiunte. Dopodiché la nuova lista breve viene ricopiata in questa issue e spuntiamo man mano che implementiamo la nuova integrazione.
